#pragma acc data copyin(a[0:10*n], b[0:10*n]) copy(max[0:10])
#pragma acc parallel loop private(temp)
#pragma acc loop vector reduction(max:temp)
#pragma acc data copyin(a[0:25*n], b[0:25*n]) copy(maximums[0:25])
#pragma acc parallel loop private(reduced)
#pragma acc loop vector reduction(max:reduced)
