#pragma acc data copyin(a,a.data[0:n], b, b.data[0:n], c, c.data[0:n], d, d.data[0:n], e, e.data[0:n], f, f.data[0:n],g, g.data[0:n])
#pragma acc parallel loop async(1)
#pragma acc parallel loop async(2)
#pragma acc parallel wait(1, 2) async(3)
#pragma acc update host(c.data[0:n]) wait(1) if(false)
#pragma acc update host(f.data[0:n]) wait(2) if(false)
#pragma acc update host(g.data[0:n]) wait(3) if(false)
#pragma acc data copyin(a[0:n], b[0:n], c[0:n], d[0:n], e[0:n], f[0:n], g[0:n])
#pragma acc parallel loop async(1)
#pragma acc parallel loop async(2)
#pragma acc parallel loop wait(1, 2) async(3)
#pragma acc update host(c[0:n]) wait(1) if(false)
#pragma acc update host(f[0:n]) wait(2) if(false)
#pragma acc update host(g[0:n]) wait(3) if(false)
#pragma acc data copyin(a[0:n], b[0:n], c, c.data[0:n], d[0:n], e[0:n], f, f.data[0:n], g, g.data[0:n])
#pragma acc parallel loop async(1)
#pragma acc parallel loop async(2)
#pragma acc parallel loop wait(1, 2) async(3)
#pragma acc update host(c.data[0:n]) wait(1) if(false)
#pragma acc update host(f.data[0:n]) wait(2) if(false)
#pragma acc update host(g.data[0:n]) wait(3) if(false)
#pragma acc data copyin(a,a.data[0:n],b,b.data[0:n],c[0:n],d,d.data[0:n],e,e.data[0:n], f[0:n], g[0:n])
#pragma acc parallel loop async(1)
#pragma acc parallel loop async(2)
#pragma acc parallel loop wait(1, 2) async(3)
#pragma acc update host(c[0:n]) wait(1) if(false)
#pragma acc update host(f[0:n]) wait(2) if(false)
#pragma acc update host(g[0:n]) wait(3) if(false)
