name: GNU CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        gnu: [7, 8, 9, 10, 11]

    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/gcc-${{ matrix.gnu }}
      CXX: /usr/bin/g++-${{ matrix.gnu }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y \
          antlr4 \
          libantlr4-runtime-dev \
          build-essential \
          g++-${{ matrix.gnu }} \
          cmake

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/
        mkdir build
        cd build
        cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON ..
        make

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        ./main.out
